/* Define variables for each gulp plugin */
var autoprefixer, browserSync, bs1, concat, dests, gulp, local, notify, sass, srcs, sync;

gulp = require('gulp');

sass = require('gulp-sass');

autoprefixer = require('gulp-autoprefixer');

notify = require('gulp-notify');

concat = require('gulp-concat');

browserSync = require('browser-sync');

bs1 = browserSync.create("first server");


/* You can also use a local url, in that case, use browserSync.init proxy: local */

local = {
  baseDir: "/"
};

srcs = {
  scss: 'scss/**/*.scss',
  docscss: 'docs/**/*.scss',
  html: '*.html',
  img: 'images/*',
  watch: {
    scss: 'scss/**/*.scss',
    docscss: 'docs/**/*.scss',
    html: 'docs/*.html',
    img: 'images/*'
  }
};

dests = {
  cssdist: 'dist/css',
  cssdocs: 'docs'
};


/* Define all your source files here */

sync = {
  css: 'docs/css/**/*.css',
  html: 'dist/*.html'
};


/* On each source file change, trigger a browsersync.reload */

gulp.task('browser-sync', function() {
  bs1.init({
    port: 3014,
    server: "./docs"
  });
  return gulp.watch(sync.css).on('change', bs1.reload);
});

gulp.task('css', function() {
  return gulp.src(srcs.scss).pipe(sass().on('error', function(err) {
    notify({
      title: 'CSS Task'
    }).write(err.line + ': ' + err.message);
    return this.emit('end');
  })).pipe(autoprefixer({
    cascade: false,
    browsers: ['> 3%']
  })).pipe(concat('alom.css')).pipe(gulp.dest(dests.cssdist)).pipe(gulp.dest(dests.cssdocs));
});

gulp.task('docscss', function() {
  return gulp.src(srcs.docscss).pipe(sass()).pipe(autoprefixer({
    cascade: false,
    browsers: ['> 3%']
  })).pipe(gulp.dest(dests.cssdocs));
});

gulp.task('html', function() {
  gulp.src(srcs.html).pipe(gulp.dest(dests.html));
  return {
    read: false
  };
});

gulp.task('watch', function() {
  gulp.watch(srcs.watch.scss, ['css']);
  gulp.watch(srcs.watch.docscss, ['docscss']);
  return gulp.watch(srcs.watch.html, ['html']);
});

gulp.task('default', ['css', 'docscss', 'browser-sync', 'watch']);

// ---
// generated by coffee-script 1.9.2
